# This is a basic workflow to help you get started with Actions

name: Boot Camp 2020

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
<<<<<<< HEAD
    - uses: actions/checkout@v2
    - name: Installing Node
      uses: actions/setup-node@v2-beta
      with: 
        node-version: v12

    # Runs a single command using the runners shell
=======
>>>>>>> d5dcbf17e846c7b9df87b6fd1c82aaa018c06cc3
    - name: Installing npm
      run: npm install --global surge

    # Runs a set of commands using the runners shell
    - name: Deploying on surge
      run: surge ./ practice-autodeploy-surge.surge.sh --token ${{ secrets.SURGE_TOKEN }}